version: "3.5"

volumes:
  postgres_volume:

services:
  air:
    build: .
    restart: always
    command: sh -c "gunicorn --bind 0.0.0.0:5000 main.wsgi"
    environment:
      - EMAIL_HOST_PASSWORD=!Qaz@Wsx
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=184290663033-ef57ci835s0oekpeoa54gfbpvks3ua7l.apps.googleusercontent.com
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=q-dIZml0PiUrn-CKPZTTyl-q
#    volumes:
#      - .:/romair
    ports:
      - 5000:5000
    depends_on:
      - redis
      - postgres

  celery:
    build: .
    restart: always
    command: celery -A main worker -l INFO
#    volumes:
#      - .:/romair
    depends_on:
      - air
      - redis    

  flower:
    build: .
    command:  celery -A main flower --port=5555
#    volumes:
#      - .:/romair
    ports:
      - 5555:5555
    depends_on:
      - air
      - redis
      - celery

  postgres:
    build: ./postgres
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=16122011

  redis:
    image: redis
    restart: always
