# Generated by Django 3.2.6 on 2021-08-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='gate',
        ),
    ]
