# Generated by Django 3.2.6 on 2021-08-25 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_flight_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='customer.gate'),
            preserve_default=False,
        ),
    ]
