# Generated by Django 3.2.6 on 2021-08-26 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ticket_gateway_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='gate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='customer.gate'),
            preserve_default=False,
        ),
    ]
