# Generated by Django 3.2.6 on 2021-08-27 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ticket_gate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.airplane')),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.seatclass')),
            ],
            options={
                'verbose_name': 'seat_number',
            },
        ),
    ]
