# Generated by Django 3.2.6 on 2021-08-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_seatnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='customer.seatnumber'),
            preserve_default=False,
        ),
    ]
