# Generated by Django 3.2.6 on 2021-08-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_ticket_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
