# Generated by Django 3.2.6 on 2021-08-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_ticket_ticket_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_code'], name='customer_ti_ticket__6572c1_idx'),
        ),
    ]
